
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/Dockerfile to edit this template

FROM java:23
ADD target/SistemaWeb-0.0.1-SNAPSHOT.jar SistemaWeb.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/SistemaWeb.jar"]